"""initial schema: users, items, document_chunks

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-18

Hand-written rather than autogenerated so every statement is deliberate — in
particular the CREATE EXTENSION, which autogenerate cannot know about, and the
HNSW index, whose operator class autogenerate would get wrong.
"""

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

# Hardcoded, NOT read from settings. A migration is a frozen snapshot of what
# was applied on a given day; if it read live config, re-running it against an
# old database after someone changed EMBEDDING_DIM would produce a schema that
# does not match what production actually has. Changing the dimension means
# writing a new migration, not editing this one — EXCEPT pre-launch, before
# any real deployment depends on this migration's history: this project has
# never shipped, so 384 (bge-small-en-v1.5, replacing the original
# text-embedding-3-small choice) is edited in place here rather than layered
# on top as a 0002 migration nobody but this repo's own dev DB will ever run.
EMBEDDING_DIM = 384


def upgrade() -> None:
    # Must precede any vector column. Supabase ships the extension available
    # but not necessarily enabled; IF NOT EXISTS makes this safe to re-run and
    # safe on a project where it was already enabled from the dashboard.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("hashed_password", sa.String(128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # Unique index rather than a plain one: it enforces the constraint AND
    # serves the login lookup, so email=? is a single index hit.
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "owner_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # Every items query filters by owner_id, so without this index the list
    # endpoint degrades into a full table scan as the table grows.
    op.create_index("ix_items_owner_id", "items", ["owner_id"])

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "owner_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(255), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_document_chunks_owner_id", "document_chunks", ["owner_id"])
    op.create_index(
        "ix_document_chunks_owner_filename", "document_chunks", ["owner_id", "filename"]
    )

    # HNSW, not IVFFlat: IVFFlat has to be built on a populated table to pick
    # useful cluster centroids, and this table starts empty. HNSW builds fine on
    # an empty table and stays correct as rows arrive.
    #
    # vector_cosine_ops MUST match the operator used at query time (<=>, cosine
    # distance). Index it with L2 and query with cosine and Postgres will just
    # ignore the index and sequentially scan — no error, only mysterious
    # slowness once the table is large.
    #
    # Honest note: at a few thousand chunks a sequential scan is already fast
    # and this index is not load-bearing. It is here because the schema should
    # be right from the start, not because this dataset needs it.
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    # Reverse creation order so foreign keys never block a drop.
    op.drop_index("ix_document_chunks_embedding_hnsw", table_name="document_chunks")
    op.drop_index("ix_document_chunks_owner_filename", table_name="document_chunks")
    op.drop_index("ix_document_chunks_owner_id", table_name="document_chunks")
    op.drop_table("document_chunks")

    op.drop_index("ix_items_owner_id", table_name="items")
    op.drop_table("items")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")

    # The vector extension is deliberately NOT dropped. It is database-wide and
    # something else may depend on it; on Supabase it is often enabled by the
    # project rather than by us, and dropping it is not ours to do.
